"""Stage C: Finalize.

- Concatenate sector drafts in order
- Append a catalyst calendar (本周关注) generated by a final LLM call that sees
  the concatenated draft + the full source bundle
- The final assembled markdown is the digest output
"""

from __future__ import annotations

import logging
import time

import anthropic

from .cost import CostLedger

logger = logging.getLogger(__name__)


CATALYST_SYSTEM = """\
You are a senior buyside analyst writing the closing 本周关注 (catalyst / week-ahead) section
of a daily research digest. The body of the digest has already been written.

Your job: read the body + raw source bundle, then output ONLY a `## 本周关注` section
listing forward-looking catalysts mentioned anywhere in the sources — earnings dates,
key conferences, expected data releases, anticipated product launches, expected guidance updates.

Output rules:
- Output ONLY `## 本周关注` heading and its bullets. No prose wrapper.
- Bullets sorted by date when explicit dates are available; otherwise group by sector.
- Each bullet: `- **<MM/DD or 本周>** — <TICKER / event> — <short relevance>`
- If no catalysts are mentioned anywhere in the sources, output `## 本周关注\n\n_本日 sources 中无明确前瞻事件。_`
- Do NOT invent catalysts. Only include items explicitly mentioned in the sources.
- Write in Chinese with English ticker / event names where natural.
"""


def run_catalyst_calendar(
    *,
    client: anthropic.Anthropic,
    model: str,
    sector_drafts: list[str],
    source_bodies_concat: str,
    ledger: CostLedger,
    max_tokens: int = 1500,
) -> str:
    """Generate the 本周关注 section. Returns the markdown string."""
    body_concat = "\n\n".join(sector_drafts)
    user_msg = (
        "## DIGEST BODY (already written)\n\n"
        f"{body_concat}\n\n"
        "## RAW SOURCES (scan for forward catalysts)\n\n"
        f"{source_bodies_concat}\n\n"
        "## OUTPUT NOW\n\nProduce the `## 本周关注` section only."
    )
    logger.info(f"Stage C catalyst calendar: calling {model}, input_chars={len(user_msg):,}")
    t0 = time.perf_counter()
    response = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        system=[{"type": "text", "text": CATALYST_SYSTEM, "cache_control": {"type": "ephemeral"}}],
        messages=[{"role": "user", "content": user_msg}],
    )
    duration = time.perf_counter() - t0
    ledger.record(stage="stage_c_catalyst", model=model, usage=response.usage,
                  duration_sec=duration, note="catalyst calendar")
    return response.content[0].text.strip()


def assemble_digest(
    *,
    target_date: str,
    sector_drafts: list[str],
    catalyst_section: str,
) -> str:
    """Final digest markdown = title + sector drafts + catalyst calendar."""
    title = f"# Daily Research Digest — {target_date}\n"
    body = "\n\n".join(sector_drafts)
    return f"{title}\n{body}\n\n{catalyst_section}\n"
